version: 2

sources:
  - name: jaffle_shop
    schema: jaffle_shop # this is the schema our raw data lives in
    database: "{{ env_var('DBT_ENVIRONMENTS') }}_BRONZE_DB" # this is the name of our database
    tables:
      - name: customers
      - name: orders
